export enum ROLE {
  superadmin = "superadmin",
}
export enum STORE_TYPE {
  owner = "Owner",
}
export enum STORAGE_TOKEN {
  superadminToken = "superadmin_token",
}
export enum ButtonE {
  button = "add_buttons",
  buttonHole = "add_buttons_holes",
  buttonThread = "add_buttons_threads",
}

export const fabricCompositions = [
  {
    _id: 1,
    fabricCategory: "Cotton",
    subFabrics: [
      "100% Cotton",
      "Cotton Poplin",
      "Cotton Poplin Lycra",
      "Cotton Mulmul (Muslin)",
      "Cotton Voile",
      "Organic Cotton Voile",
      "Cotton Twill",
      "Cotton Twill Lycra",
      "Cotton Lawn",
      "Cotton Cambric",
      "Giza Cotton Satin",
      "Cotton Linen",
      "Cotton Sheeting",
      "Cotton Silk",
      "Cotton Duck Canvas",
      "Cotton Single Jersey",
      "Cotton Lycra Spandex",
      "Cotton French Terry",
      "Cotton Slub",
      "Cotton Slub Jersey",
      "Cotton Jersey Pique",
      "Cotton Flex",
      "Cotton Satin",
      "Cotton Satin Lycra",
      "Premium Cotton Satin",
      "Cotton Lurex",
      "Cotton Drill",
      "Seersucker Cotton",
    ],
  },
  {
    _id: 2,
    fabricCategory: "Viscose",
    subFabrics: [
      "100% Viscose",
      "Viscose Crepe",
      "Viscose Royal Crepe",
      "Viscose Moss Crepe",
      "Viscose Moss Satin",
      "Viscose Georgette",
      "Viscose Cotton Georgette",
      "Viscose Chiffon",
      "Viscose Lycra Spandex",
      "Viscose Slub",
      "Viscose Twill",
      "Viscose Lawn",
      "Viscose Poplin",
      "Viscose Marocaine",
      "Viscose Satin",
    ],
  },
  {
    _id: 3,
    fabricCategory: "Silk",
    subFabrics: [
      "Silk Satin",
      "Silk Chanderi",
      "Silk Habotai",
      "Silk Tabby",
      "Silk Flat Chiffon",
      "Silk Crepe",
      "Silk Organza",
      "Silk Georgette",
      "Silk Twill",
      "Raw Silk",
      "Silk Crepe",
      "Mulberry Silk",
      "Peace Silk (Ahimsa)",
      "Silk Brocade",
      "Silk Jersey",
      "Silk Wool",
      "Taffeta Silk",
      "Silk Velvet",
    ],
  },
  {
    _id: 4,
    fabricCategory: "Rayon",
    subFabrics: ["100% Rayon", "Rayon Flex", "Rayon Challis", "Rayon Crepe"],
  },
  {
    _id: 5,
    fabricCategory: "Polyester",
    subFabrics: [
      "100% Polyester",
      "Polyester Satin",
      "Polyester Velvet",
      "Polyester Lycra Spandex",
      "Polyester Georgette",
      "Poly Georgette Satin",
      "Polyester Chiffon",
      "Polyester Crepe",
      "Polyester Duck",
      "Polyester Taffeta",
      "100% Polyester Herpa",
      "Polyester Mesh",
    ],
  },
  {
    _id: 6,
    fabricCategory: "Modal",
    subFabrics: ["100% Modal", "Modal Muslin", "Modal Satin"],
  },
  {
    _id: 7,
    fabricCategory: "Bamboo",
    subFabrics: [
      "100% Bamboo",
      "100% Bamboo Stripe",
      "Bamboo Muslin",
      "Bamboo Silk",
      "Bamboo Lycra",
      "Bamboo Jersey",
      "Bamboo Lycra Jersey",
      "Bamboo Lyocell",
    ],
  },
  {
    _id: 8,
    fabricCategory: "100% Linen",
    subFabrics: ["100% Linen", "Linen Cotton Canvas"],
  },
  {
    _id: 9,
    fabricCategory: "100% Tencel Satin",
    subFabrics: ["100% Tencel Satin"],
  },
  {
    _id: 10,
    fabricCategory: "Nylon",
    subFabrics: ["Nylon", "Nylon mesh"],
  },
  {
    _id: 11,
    fabricCategory: "Denim",
    subFabrics: ["Polyester Denim", "Cotton Denim"],
  },
  {
    _id: 12,
    fabricCategory: "Leather",
    subFabrics: ["Leather"],
  },
  {
    _id: 13,
    fabricCategory: "Oxford",
    subFabrics: ["Oxford"],
  },
  {
    _id: 14,
    fabricCategory: "Wool",
    subFabrics: ["100% Wool"],
  },
];
